pages:
    stage: deploy
    script:
    - mkdir public
    - cp -r entscheidungshilfe-lehre/* public/  # all content moved from entscheidungshilfe-lehre
    - mv public/app.html public/index.html # app.html renamed so that it appears as the default page
    artifacts:
        paths:
        - public
    only:
    - new-question-flow
